name = "daemon"
main = "src/mcp-worker.ts"
compatibility_date = "2025-08-20"

[[kv_namespaces]]
binding = "KV"
id = "901f02847dec42f18ed4dedf7054af08"

[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"
run_worker_first = true
