/**
 * Freshness + provenance guard for canonical daemon answers.
 *
 * T-100 fix: every canonical-context answer is served from a frozen build-time
 * snapshot (src/generated/daemon-data.ts). Without a freshness/emptiness check at
 * call time, a stale or empty section is returned as an authoritative fact — the
 * "returned a 2-year-old memoir title" failure class, and the "whoIAm: '' served
 * as a valid answer" failure class.
 *
 * This module is pure (no Worker globals, no I/O) so the staleness/emptiness logic
 * is unit-testable. `now` is injectable for deterministic tests; in the Worker it
 * defaults to the real clock (fine — this is a Worker, not a restricted workflow).
 */

/** Age budget for canonical content before it is flagged stale. */
export const FRESHNESS_BUDGET_DAYS = 14;

export interface Provenance {
  /** Date the underlying daemon.md was last edited (YYYY-MM-DD), from its footer. */
  last_updated: string;
  /** ISO timestamp the snapshot was generated by the parser, if known. */
  generated_at: string | null;
  /** Whole days between `now` and `last_updated`; null if `last_updated` unparseable. */
  age_days: number | null;
  /** The budget the age is measured against. */
  budget_days: number;
  /** True when age_days exceeds budget_days. */
  stale: boolean;
}

/** A section value counts as unpopulated when it is empty or whitespace-only. */
export function isUnpopulated(value: string | null | undefined): boolean {
  return !value || value.trim().length === 0;
}

/** Whole days between `now` and an ISO/`YYYY-MM-DD` date; null if unparseable. */
export function ageInDays(lastUpdated: string, now: Date = new Date()): number | null {
  const then = Date.parse(lastUpdated);
  if (Number.isNaN(then)) return null;
  return Math.floor((now.getTime() - then) / 86_400_000);
}

/** Compute provenance + staleness for a snapshot's last-updated date. */
export function computeProvenance(
  lastUpdated: string,
  generatedAt: string | null = null,
  now: Date = new Date(),
  budgetDays: number = FRESHNESS_BUDGET_DAYS,
): Provenance {
  const age = ageInDays(lastUpdated, now);
  return {
    last_updated: lastUpdated,
    generated_at: generatedAt,
    age_days: age,
    budget_days: budgetDays,
    stale: age !== null && age > budgetDays,
  };
}

export interface SectionResult {
  content: { type: 'text'; text: string }[];
  provenance: Provenance;
  stale: boolean;
  /** Present only when the section had no canonical content. */
  status?: 'unpopulated';
  /** Present only when the content is stale — loud, but not a refusal. */
  warning?: string;
}

/**
 * Build an MCP tool result for a canonical section, carrying provenance.
 *
 * - Empty/whitespace content returns `status: 'unpopulated'` so "missing fact" is
 *   distinguishable from "blank fact" — it is NOT returned as a valid answer.
 * - Stale content is returned WITH a loud `stale: true` + warning (never refused —
 *   a refusing daemon could break callers; a visible flag is the fix).
 * - `content` shape is preserved so existing callers keep working; every new
 *   signal is additive.
 */
export function buildSectionResult(
  rawText: string,
  sectionName: string,
  lastUpdated: string,
  generatedAt: string | null = null,
  now: Date = new Date(),
): SectionResult {
  const provenance = computeProvenance(lastUpdated, generatedAt, now);

  if (isUnpopulated(rawText)) {
    return {
      status: 'unpopulated',
      content: [{
        type: 'text',
        text: `Section "${sectionName}" is unpopulated — no canonical content on record. This is a missing fact, not a blank answer; do not present it as authoritative.`,
      }],
      provenance,
      stale: provenance.stale,
    };
  }

  const result: SectionResult = {
    content: [{ type: 'text', text: rawText }],
    provenance,
    stale: provenance.stale,
  };

  if (provenance.stale) {
    result.warning =
      `STALE: canonical content last updated ${lastUpdated}` +
      (provenance.age_days !== null ? ` (${provenance.age_days} days ago, budget ${provenance.budget_days} days)` : '') +
      `. This snapshot may be out of date — verify against a live source before relying on it.`;
  }

  return result;
}
